### ISSUE TITLE
Не работает редактирование карточки

### ISSUE THREAD

**Issue by arykovsb** [mamonovv/Trello#1]
Chrome. Дважды щелкаю на карточку, открывается модальное окно редактирования. 

- [x] Меняю название карточки. Нет кнопки "Сохранить" (т.е. невозможно изменить только название)
- [x] Меняю текст карточки. Кнопка Сохранить появляется. Нажимаю ее. Ничего не происходит. Окно не закрывается. Изменения не сохраняются.

**Comment by mamonovv** [comment]
Вообщем, думал сегодня сделать задачу с popUp Окном для карточек, но не тут то было

В целом, я сначала сделал дизайн, тут особо ничего сложного, просто  немного муторно, но когда я начал связывать все с БД, началось что то странное

Я в прошлых своих fetch запросах использовал FormData, это обработчик форм для js, собственно до этого все работало

Но сейчас, он почему то перестал забирать данные из формы, я проверил уже несколько раз и форму и то как я этот запрос строю в Js, все верно, но когда я на сервер отправляю запрос, он отправляет один csrf токен без всего остального и я не понимаю почему

Вообщем я гдето 5 часов посидел над этим

**Comment by mamonovv** [comment]
Вчера вечером еще 3 часа потратил на это, перечитал теорию, посмотрел код, как я до этого делал, когда работает, как написал и ничего

Наверное единственное, что странно, иногда форма не захватывается, т.е. объект формы есть, а внутри ничего, никаких инпутов. А иногда нормально и я не понимаю от чего это зависит

Ну и к тому же, знаю что объект FormData Всегда захватывает input с Csrf токеном, т.е. форма сущетсвует все равно, даже когда он показывает что объект формы пустой

**Comment by mamonovv** [comment]
Посидел сегодня еще часа 4, в итоге разобрался в причине

Я создал отдельный HTML, попробовал запустить на нем форму, не получилось. В итоге случайно просто заметил свойство name, ради любопытства решил добавить и оно заработало. Собственно я и думал, что ошибка будет примитивной, но не очевидной

Теперь popUpы работют, исключая дату и фото. Дата запоминается, но не может передаться обратно, т.к. не тот формат, а фото пока не разобрался как отправлять/получать

**Comment by arykovsb** [comment]
1. Вот [https://learn.javascript.ru/formdata](https://learn.javascript.ru/formdata) свойство name вроде не используют. просто передают форму. почему оно работает тогда?
2. Вы говорили, что с другой формой у вас все работало. не работало только в попапе. так вот, в той другой форме вы же тоже не использовали name. как оно там тогда работало?

**Comment by mamonovv** [comment]
Я говорю о свойстве name у input, по ссылке в примерах оно есть. К тому же у меня в формах оно тоже присутвовало.

**Comment by mamonovv** [comment]
Закончил работу над popUp окнами для карточек.

**Comment by arykovsb** [comment]
Учтено 12 ч.
