### ISSUE TITLE
Многократный запрос AJAX

### ISSUE THREAD

**Issue by arykovsb** [mamonovv/Trello#2]
- [x] При удалении колонки
- [x] При переносе карточки между колонками

Так происходит из-за того, что на кнопку X вешается множество событий eventListener, а должно быть только одно. Аналогично и с переносом карточки.

**Comment by mamonovv** [comment]
All fixed

Потратил 1-2 часа

**Comment by arykovsb** [comment]
Учтено 1.5 ч.
