### ISSUE TITLE
Изучить работу настоящего Trello

### ISSUE THREAD

**Issue by arykovsb** [mamonovv/Trello#3]
- [x] Посмотреть, как они делают добавление/удаление карточек и задач
- [x] Посмотреть, какая у них структура API

Описать здесь результаты. Может какие-то идеи в проект возьмете.

**Comment by arykovsb** [comment]
Владислав, по этой задаче что-то делается? Не обязательно сразу конечный результат постить. Закиньте что-то промежуточное. Что вы уже успели поисследовать и понять.

**Comment by mamonovv** [comment]
Когда нажимаю на поле добавления карточки происходит запрос на сервер batch на api trello (fetch), который длится пока я не нажму добавить на карточке

При нажатии - добавить, отправляется запрос cards(xhr)и добавляется карточка

При нажатии на карточку - происходит загрузка данных карточек по уникальному очень длинному url, после загрузки снова появляется метод batch

Когда начинаю редактировать поля появляется снова метод batch, потом editing и длится пока я не закончу и не отправлю изменение
После этого повторно отправляется editing, снова берутся данные карточки по уникальному url И появляется слушатель batch и так для каждого пункта

При удалении карточки происходит batch - появляется меню подтверждения, когда подтверждаешь идет отправка данных по уникальному url и после окончания появляется метод batch




При перетаскиваниии карточек ничего не происходит, пока не поместишь карточку на место. Как только помещаешь - идет запрос по уникальному url , после появляется batch

При добавлении новой колонки - отправляется запрос на lists, после этого появляется batch

При переименовании доски отправляется запрос на уникальный URL, потом слушатель batch


Все изменения были инциированы файлом - Instrument.js

В файле были описаны инструменты API:
 * Instrument native APIs to call handlers that can be used to create breadcrumbs, APM spans etc.
 *  - Console API
 *  - Fetch API
 *  - XHR API
 *  - History API
 *  - DOM API (click/typing)
 *  - Error API
 *  - UnhandledRejection API
 */

Все это работает через switch, в который принимаются названия этих api

Примерно час на просмотр всего изучение ушло. Забавно, в их коде даже заметки TODO есть, видно что даже сейчас все в работе)

**Comment by arykovsb** [comment]
Учтен 1 ч. 

Самое интересное: после того, как вы это изучили, какие можно сделать выводы? Как вы считаете, что сделано в вашем API правильно, а что стоит переделать? Почему?

**Comment by mamonovv** [comment]
Ну вообще у меня довольно похожу сделано, наверное самое такое большое отличие, что там сохранение происходит отдельно для каждого поля, т.е. имя карточки сразу , описание сразу, судя по запросам, хотя после все равно нужно подтвердить на кнопку

В целом все то же самое у меня, даже не знаю что можно поменять, разве что в отдельный api какие то функции выносить, возможно

**Comment by arykovsb** [comment]
Что насчет передачи параметров? Как именно они передаются?

Что насчет идентификации досок/карточек/задач? Как именно эти ID передаются (через get-параметры, URL, в теле POST или еще как-то)?
