### ISSUE TITLE
Познакомиться с Bootstrap 5

### ISSUE THREAD

**Issue by arykovsb** [mamonovv/Trello#7]
[Задание](https://wiki.iaud.ru/doku.php?id=kb:curriculum:web_dev_2#bootstrap)

**Comment by mamonovv** [comment]
Прошел туториал, если честно он довольно сомниетльного качества, т.к. особо ничего не объяснено и в коде, который приведен имеются ошибки...

https://github.com/mamonovv/bootstrapTutorial

Потратил на это час, нормально познакомлюсь с Bootstrap5 когда буду переделывать проект, так сказать на практике

**Comment by arykovsb** [comment]
Там в списке есть еще туториал по Bootstrap 5 на английском. А также учебник по Bootstrap 4. Он вполне пригодный, но версия старая. Хотя в базовых вопросах там все одинаковое. Можете с этим материалом еще познакомиться.

Конечно, на практике лучше всего учиться. Но про некоторые концепции (типа сеток Bootstrap) лучше почитать заранее.

**Comment by mamonovv** [comment]
Прошел туториал по Bootstrap5, в котором все азы были ззатронуты. 
Вот само видео - https://www.youtube.com/watch?v=CvMxvb2D8Iw

А вот репозиторий с тем, что в итоге вышло - https://github.com/mamonovv/bootstrap5-practice

Завтра начну переносить проект на Boostrap, если не будет аномалий - перенесу завтра полностью

Потратил на полное понимание Bootstrap - 3 часа

**Comment by mamonovv** [comment]
Полностью перенес проект на Bootstrap 5, теперь он адаптивный. В некоторых местах изменил стиль, например поле с досками, теперь выглядит намного приятнее. К тому же добавил для досок возможность удаления.

Потратил на перенос - 12 часов. В сумме на задачу ушло - 16 часов

**Comment by arykovsb** [comment]
Учтено 16 ч.
