### ISSUE TITLE
Познакомиться с Vue

### ISSUE THREAD

**Issue by arykovsb** [mamonovv/Trello#9]
[Задание](https://wiki.iaud.ru/doku.php?id=kb:curriculum:web_dev_2#vue)

**Comment by mamonovv** [comment]
Прошел задание с Vue

https://codesandbox.io/s/recursing-keller-mw230?file=/src/components/HelloWorld.vue
https://codesandbox.io/s/charming-hooks-5zp37?file=/src/components/HelloWorld.vue
Разбил задания на 2 части , чтобы удобнее было

потратил на все 11 часов
